version: '3.8'

services:
  backend:
    image: task-manager-backend
    container_name: task-manager-backend-container
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - mongodb+srv://janani:iCk7U9FzYghY8Yib@cluster0.s0wzc.mongodb.net/task-manager-nodejs?retryWrites=true&w=majority

  frontend:
    image: task-manager-frontend
    container_name: task-manager-frontend-container
    build:
      context: ./task-manager-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
